// Lingua Inglese
const en_translations = {
    // Esistenti
    menuTitle: 'Menu',
    navPubblici: 'Public',
    navCercaPersone: 'Find People',
    navMessaggi: 'Messages',
    navPosta: 'Mail',
    navSegnalazioni: 'Reports',
    navProfilo: 'Profile',
    navImpostazioni: 'Settings',
    navAdmin: 'User Management',
    logout: 'Logout',
    impostazioniTitle: 'Settings',
    impostazioniDesc: 'Configure your account preferences.',
    backgroundTitle: 'Background Color',
    deleteAccountTitle: 'Delete Account',
    deleteAccountDesc: 'This action is irreversible. It will permanently delete your account and all associated data.',
    deleteAccountBtn: 'Delete my account',
    modalTitle: 'Are you sure?',
    modalDesc: 'Do you really want to delete your account? This action cannot be undone.',
    modalCancelBtn: 'Cancel',
    modalConfirmBtn: 'Delete',

    // Profilo
    profileTitle: 'Profile - Spottio',
    followerCount: 'Followers',
    followingCount: 'Following',
    editBio: 'Edit Bio',
    reportManagementAdmin: 'Report Management (Admin)',
    save: 'Save',
    myPublishedPosts: 'My Published Posts',
    users: 'Users',

    // Pubblici
    publics: 'Public',
    confirmDeletion: 'Confirm Deletion',
    deletePostWarning: 'Are you sure you want to delete this post? This action is irreversible.',
    cancel: 'Cancel',
    delete: 'Delete',
    reportPost: 'Report Post',
    reportReason: 'Reason for reporting:',
    selectReason: 'Select a reason',
    inappropriateContent: 'Inappropriate content',
    spam: 'Spam',
    offensiveLanguage: 'Offensive language',
    other: 'Other',
    descriptionOptional: 'Description (optional):',
    addDetails: 'Add details...',
    submit: 'Submit',
    editPost: 'Edit Post',
    category: 'Category',
    general: 'General',
    postText: 'Post text:',

    // Segnalazioni
    reports: 'Reports',
    reportManagement: 'Report Management',
    totalReports: 'Total reports:',
    deleteAllReports: 'Delete all reports',

    // Posta
    createPost: 'Create Post',
    tellSomething: 'Tell us something...',
    addMedia: 'Add Media',
    publish: 'Publish',

    // Cerca Persone
    searchPeople: 'Find People',
    search: 'Search...',
    loadingUsers: 'Loading users...',

    // Chat / Messaggi
    messagesTitle: 'Messages',
    chat: 'Chat',
    newGroup: 'New Group',
    searchPeopleOrGroups: 'Search people or groups...',
    defaultBackground: 'Default Background',
    uploadImage: 'Upload image...',
    selectChatPrompt: 'Select a chat or group to start a conversation.',
    writeMessage: 'Write a message...',
    send: 'Send',
    createNewGroup: 'Create a new Group',
    groupName: 'Group name...',
    searchMembersToAdd: 'Search members to add...',
    selectedMembers: 'Selected members:',
    create: 'Create',
    groupInfo: 'Group Info',
    editGroupName: 'Edit group name',
    participants: 'Participants:',
    adminPanelAddMember: 'Admin Panel: Add Member',
    usernameToAdd: 'Username to add...',
    add: 'Add',
    leave: 'Leave',
    close: 'Close'
};