// Lingua Spagnola
const es_translations = {
    // Esistenti
    menuTitle: 'Menú',
    navPubblici: 'Público',
    navCercaPersone: 'Buscar Personas',
    navMessaggi: 'Mensajes',
    navPosta: 'Correo',
    navSegnalazioni: 'Informes',
    navProfilo: 'Perfil',
    navImpostazioni: 'Configuración',
    navAdmin: 'Gestión de Usuarios',
    logout: 'Cerrar sesión',
    impostazioniTitle: 'Configuración',
    impostazioniDesc: 'Configura las preferencias de tu cuenta.',
    backgroundTitle: 'Color de Fondo',
    deleteAccountTitle: 'Eliminar Cuenta',
    deleteAccountDesc: 'Esta acción es irreversible. Eliminará permanentemente su cuenta y todos los datos asociados.',
    deleteAccountBtn: 'Eliminar mi cuenta',
    modalTitle: '¿Estás seguro?',
    modalDesc: '¿De verdad quieres eliminar tu cuenta? Esta acción no se puede deshacer.',
    modalCancelBtn: 'Cancelar',
    modalConfirmBtn: 'Eliminar',

    // Profilo
    profileTitle: 'Perfil - Spottio',
    followerCount: 'Seguidores',
    followingCount: 'Siguiendo',
    editBio: 'Editar Bio',
    reportManagementAdmin: 'Gestión de Informes (Admin)',
    save: 'Guardar',
    myPublishedPosts: 'Mis Publicaciones',
    users: 'Usuarios',

    // Pubblici
    publics: 'Público',
    confirmDeletion: 'Confirmar Eliminación',
    deletePostWarning: '¿Estás seguro de que deseas eliminar esta publicación? Esta acción es irreversible.',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    reportPost: 'Reportar Publicación',
    reportReason: 'Motivo del reporte:',
    selectReason: 'Seleccione un motivo',
    inappropriateContent: 'Contenido inapropiado',
    spam: 'Spam',
    offensiveLanguage: 'Lenguaje ofensivo',
    other: 'Otro',
    descriptionOptional: 'Descripción (opcional):',
    addDetails: 'Añadir detalles...',
    submit: 'Enviar',
    editPost: 'Editar Publicación',
    category: 'Categoría',
    general: 'General',
    postText: 'Texto de la publicación:',

    // Segnalazioni
    reports: 'Informes',
    reportManagement: 'Gestión de Informes',
    totalReports: 'Total de informes:',
    deleteAllReports: 'Eliminar todos los informes',

    // Posta
    createPost: 'Crear Publicación',
    tellSomething: 'Cuéntanos algo...',
    addMedia: 'Añadir Medio',
    publish: 'Publicar',

    // Cerca Persone
    searchPeople: 'Buscar Personas',
    search: 'Buscar...',
    loadingUsers: 'Cargando usuarios...',

    // Chat / Messaggi
    messagesTitle: 'Mensajes',
    chat: 'Chat',
    newGroup: 'Nuevo Grupo',
    searchPeopleOrGroups: 'Buscar personas o grupos...',
    defaultBackground: 'Fondo Predeterminado',
    uploadImage: 'Subir imagen...',
    selectChatPrompt: 'Selecciona un chat o grupo para empezar a conversar.',
    writeMessage: 'Escribe un mensaje...',
    send: 'Enviar',
    createNewGroup: 'Crear un nuevo Grupo',
    groupName: 'Nombre del grupo...',
    searchMembersToAdd: 'Buscar miembros para añadir...',
    selectedMembers: 'Miembros seleccionados:',
    create: 'Crear',
    groupInfo: 'Info del Grupo',
    editGroupName: 'Editar nombre del grupo',
    participants: 'Participantes:',
    adminPanelAddMember: 'Panel de Admin: Añadir Miembro',
    usernameToAdd: 'Nombre de usuario a añadir...',
    add: 'Añadir',
    leave: 'Abandonar',
    close: 'Cerrar'
};