export default {
    spotTitle: 'سبوت - Spottio',
    tabExplore: 'استكشف',
    tabFollowing: 'المتابعون',
    yourFlashspot: 'قصتك اليومية',
    noSpotsAvailable: 'لا توجد منشورات متاحة.',
    noFollowingSpots: 'أنت لا تتابع أحداً بعد. انتقل إلى استكشف لاكتشاف محتوى جديد!',
    anonymousUser: 'مجهول',
    reportBtn: 'إبلاغ',
    editPostBtn: 'تعديل',
    deletePostBtn: 'حذف',
    mediaCountWord: 'وسائط',
    shareBtn: 'مشاركة',
    likesModalTitle: 'الإعجابات',
    noLikesYet: 'لا توجد إعجابات بعد.',
    loading: 'جاري التحميل...',
    commentsTitle: 'التعليقات',
    firstCommentPrompt: 'لا توجد تعليقات. كن أول من يعلق!',
    noComments: 'لا توجد تعليقات متاحة.',
    writeCommentPlaceholder: 'اكتب تعليقاً...',
    sendCommentBtn: 'إرسال',
    cancelBtn: 'إلغاء',
    saveBtn: 'حفظ',

    reportModalTitle: 'إبلاغ عن المنشور',
    reportModalSubtitle: 'ساعدنا في فهم المشكلة المتعلقة بهذا المحتوى.',
    reportReason: 'السبب',
    reportReasonSelect: 'اختر فئة...',
    reportCopyright: 'انتهاك حقوق الطبع والنشر',
    reportGdpr: 'انتهاك الخصوصية / البيانات الشخصية (GDPR)',
    reportHarassment: 'مضايقة أو تهديد أو كراهية',
    reportSpam: 'رسائل غير مرغوب فيها أو احتيال',
    reportOther: 'محتوى غير مهم',
    reportDetails: 'تفاصيل إضافية (اختياري)',
    reportDetailsPlaceholder: 'قدم معلومات إضافية...',
    sendReportBtn: 'إرسال البلاغ'
};