export default {
    spotTitle: 'Spots - Spottio',
    tabExplore: 'Explore',
    tabFollowing: 'Following',
    yourFlashspot: 'Your Flashspot',
    noSpotsAvailable: 'No spots available.',
    noFollowingSpots: 'You are not following anyone yet. Go to Explore to discover new content!',
    anonymousUser: 'Anonymous',
    reportBtn: 'Report',
    editPostBtn: 'Edit',
    deletePostBtn: 'Delete',
    mediaCountWord: 'media',
    shareBtn: 'Share',
    likesModalTitle: 'Likes',
    noLikesYet: 'No likes yet.',
    loading: 'Loading...',
    commentsTitle: 'Comments',
    firstCommentPrompt: 'No comments yet. Be the first to comment!',
    noComments: 'No comments available.',
    writeCommentPlaceholder: 'Write a comment...',
    sendCommentBtn: 'Send',
    cancelBtn: 'Cancel',
    saveBtn: 'Save',
    
    reportModalTitle: 'Report Spot',
    reportModalSubtitle: 'Help us understand the issue with this content.',
    reportReason: 'Reason',
    reportReasonSelect: 'Select a category...',
    reportCopyright: 'Copyright violation',
    reportGdpr: 'Privacy / Personal Data violation (GDPR)',
    reportHarassment: 'Harassment, threats, or hate',
    reportSpam: 'Spam or fraud',
    reportOther: 'Irrelevant or trivial content',
    reportDetails: 'Additional details (Optional)',
    reportDetailsPlaceholder: 'Provide additional information...',
    sendReportBtn: 'Submit Report'
};