export default {
    spotTitle: 'Spots - Spottio',
    tabExplore: 'Explorar',
    tabFollowing: 'Siguiendo',
    yourFlashspot: 'Tu Flashspot',
    noSpotsAvailable: 'No hay spots disponibles.',
    noFollowingSpots: '¡Aún no sigues a nadie. Ve a Explorar para descubrir contenido!',
    anonymousUser: 'Anónimo',
    reportBtn: 'Denunciar',
    editPostBtn: 'Editar',
    deletePostBtn: 'Eliminar',
    mediaCountWord: 'archivos',
    shareBtn: 'Compartir',
    likesModalTitle: 'Me gusta',
    noLikesYet: 'Aún no hay "me gusta".',
    loading: 'Cargando...',
    commentsTitle: 'Comentarios',
    firstCommentPrompt: 'No hay comentarios. ¡Sé el primero en comentar!',
    noComments: 'No hay comentarios disponibles.',
    writeCommentPlaceholder: 'Escribe un comentario...',
    sendCommentBtn: 'Enviar',
    cancelBtn: 'Cancelar',
    saveBtn: 'Guardar',

    reportModalTitle: 'Denunciar Spot',
    reportModalSubtitle: 'Ayúdanos a entender el problema con este contenido.',
    reportReason: 'Motivo',
    reportReasonSelect: 'Selecciona una categoría...',
    reportCopyright: 'Infracción de derechos de autor',
    reportGdpr: 'Violación de privacidad / Datos personales (GDPR)',
    reportHarassment: 'Acoso, amenazas u odio',
    reportSpam: 'Spam o fraude',
    reportOther: 'Contenido irrelevante o inapropiado',
    reportDetails: 'Detalles adicionales (Opcional)',
    reportDetailsPlaceholder: 'Proporciona más información...',
    sendReportBtn: 'Enviar Denuncia'
};