export default {
    spotTitle: 'Spots - Spottio',
    tabExplore: 'Explorer',
    tabFollowing: 'Abonnements',
    yourFlashspot: 'Votre Flashspot',
    noSpotsAvailable: 'Aucun spot disponible.',
    noFollowingSpots: 'Vous ne suivez personne pour le moment. Allez sur Explorer !',
    anonymousUser: 'Anonyme',
    reportBtn: 'Signaler',
    editPostBtn: 'Modifier',
    deletePostBtn: 'Supprimer',
    mediaCountWord: 'médias',
    shareBtn: 'Partager',
    likesModalTitle: 'J\'aime',
    noLikesYet: 'Aucun "j\'aime" pour le moment.',
    loading: 'Chargement...',
    commentsTitle: 'Commentaires',
    firstCommentPrompt: 'Aucun commentaire. Soyez le premier à commenter !',
    noComments: 'Aucun commentaire disponible.',
    writeCommentPlaceholder: 'Écrire un commentaire...',
    sendCommentBtn: 'Envoyer',
    cancelBtn: 'Annuler',
    saveBtn: 'Enregistrer',

    reportModalTitle: 'Signaler le Spot',
    reportModalSubtitle: 'Aidez-nous à comprendre le problème avec ce contenu.',
    reportReason: 'Motif',
    reportReasonSelect: 'Sélectionnez une catégorie...',
    reportCopyright: 'Atteinte aux droits d\'auteur',
    reportGdpr: 'Violation de confidentialité / Données personnelles (RGPD)',
    reportHarassment: 'Harcèlement, menaces ou haine',
    reportSpam: 'Spam ou escroquerie',
    reportOther: 'Contenu non pertinent',
    reportDetails: 'Détails supplémentaires (Optionnel)',
    reportDetailsPlaceholder: 'Fournissez plus d\'informations...',
    sendReportBtn: 'Envoyer le Signalement'
};