export default {
    spotTitle: 'स्पॉट्स - Spottio',
    tabExplore: 'एक्सप्लोर करें',
    tabFollowing: 'फ़ॉलो कर रहे हैं',
    yourFlashspot: 'आपका फ़्लैशस्पॉट',
    noSpotsAvailable: 'कोई स्पॉट उपलब्ध नहीं है।',
    noFollowingSpots: 'आप अभी किसी को फ़ॉलो नहीं कर रहे हैं। नई सामग्री खोजने के लिए एक्सप्लोर पर जाएं!',
    anonymousUser: 'अनाम',
    reportBtn: 'रिपोर्ट करें',
    editPostBtn: 'संपादित करें',
    deletePostBtn: 'हटाएं',
    mediaCountWord: 'मीडिया',
    shareBtn: 'साझा करें',
    likesModalTitle: 'पसंद',
    noLikesYet: 'अभी तक कोई पसंद नहीं।',
    loading: 'लोड हो रहा है...',
    commentsTitle: 'टिप्पणियाँ',
    firstCommentPrompt: 'कोई टिप्पणी नहीं है। सबसे पहले टिप्पणी करें!',
    noComments: 'कोई टिप्पणी उपलब्ध नहीं है।',
    writeCommentPlaceholder: 'एक टिप्पणी लिखें...',
    sendCommentBtn: 'भेजें',
    cancelBtn: 'रद्द करें',
    saveBtn: 'सहेजें',

    reportModalTitle: 'स्पॉट की रिपोर्ट करें',
    reportModalSubtitle: 'इस सामग्री में समस्या समझने में हमारी सहायता करें।',
    reportReason: 'कारण',
    reportReasonSelect: 'एक श्रेणी चुनें...',
    reportCopyright: 'कॉपीराइट उल्लंघन',
    reportGdpr: 'गोपनीयता / व्यक्तिगत डेटा उल्लंघन (GDPR)',
    reportHarassment: 'उत्पीड़न, धमकी या घृणा',
    reportSpam: 'स्पैम या धोखाधड़ी',
    reportOther: 'अप्रासंगिक सामग्री',
    reportDetails: 'अतिरिक्त विवरण (वैकल्पिक)',
    reportDetailsPlaceholder: 'अतिरिक्त जानकारी दें...',
    sendReportBtn: 'रिपोर्ट भेजें'
};