export default {
    spotTitle: 'Spot - Spottio',
    tabExplore: 'Esplora',
    tabFollowing: 'Seguiti',
    yourFlashspot: 'Il tuo Flashspot',
    noSpotsAvailable: 'Nessuno spot disponibile.',
    noFollowingSpots: 'Non segui ancora nessuno. Vai su Esplora per scoprire nuovi contenuti!',
    anonymousUser: 'Anonimo',
    reportBtn: 'Segnala',
    editPostBtn: 'Modifica',
    deletePostBtn: 'Elimina',
    mediaCountWord: 'media',
    shareBtn: 'Condividi',
    likesModalTitle: 'Mi piace',
    noLikesYet: 'Nessun "mi piace" ancora.',
    loading: 'Caricamento...',
    commentsTitle: 'Commenti',
    firstCommentPrompt: 'Nessun commento. Sii il primo a commentare!',
    noComments: 'Nessun commento disponibile.',
    writeCommentPlaceholder: 'Scrivi un commento...',
    sendCommentBtn: 'Invia',
    cancelBtn: 'Annulla',
    saveBtn: 'Salva',
    
    // Modale Segnalazione Condivisa
    reportModalTitle: 'Segnala Spot',
    reportModalSubtitle: 'Aiutaci a comprendere il problema con questo contenuto.',
    reportReason: 'Motivo',
    reportReasonSelect: 'Seleziona una categoria...',
    reportCopyright: 'Violazione Copyright / Diritto d\'autore',
    reportGdpr: 'Violazione Privacy / Dati Personali (GDPR)',
    reportHarassment: 'Molestie, Minacce o Odio',
    reportSpam: 'Spam o Truffa',
    reportOther: 'Contenuto irrilevante o futile',
    reportDetails: 'Dettagli aggiuntivi (Opzionale)',
    reportDetailsPlaceholder: 'Fornisci ulteriori informazioni...',
    sendReportBtn: 'Invia Segnalazione'
};