export default {
    spotTitle: 'スポット - Spottio',
    tabExplore: '見つける',
    tabFollowing: 'フォロー中',
    yourFlashspot: 'あなたのフラッシュスポット',
    noSpotsAvailable: 'スポットがありません。',
    noFollowingSpots: 'まだ誰もフォローしていません。見つけるタブから新しい投稿を探しましょう！',
    anonymousUser: '匿名',
    reportBtn: '報告',
    editPostBtn: '編集',
    deletePostBtn: '削除',
    mediaCountWord: 'メディア',
    shareBtn: '共有',
    likesModalTitle: 'いいね',
    noLikesYet: 'まだいいねがありません。',
    loading: '読み込み中...',
    commentsTitle: 'コメント',
    firstCommentPrompt: 'コメントはありません。最初のコメントを投稿しましょう！',
    noComments: 'コメントがありません。',
    writeCommentPlaceholder: 'コメントを入力...',
    sendCommentBtn: '送信',
    cancelBtn: 'キャンセル',
    saveBtn: '保存',

    reportModalTitle: 'スポットを報告',
    reportModalSubtitle: 'このコンテンツの問題点をお知らせください。',
    reportReason: '理由',
    reportReasonSelect: 'カテゴリーを選択...',
    reportCopyright: '著作権の侵害',
    reportGdpr: 'プライバシー / 個人情報の侵害 (GDPR)',
    reportHarassment: '嫌がらせ、脅迫、またはヘイトスピーチ',
    reportSpam: 'スパムまたは詐欺',
    reportOther: '不適切な内容',
    reportDetails: '詳細情報（任意）',
    reportDetailsPlaceholder: '詳細を入力してください...',
    sendReportBtn: '報告を送信'
};