export default {
    spotTitle: '스팟 - Spottio',
    tabExplore: '탐색',
    tabFollowing: '팔로잉',
    yourFlashspot: '내 플래시스팟',
    noSpotsAvailable: '표시할 스팟이 없습니다.',
    noFollowingSpots: '아직 아무도 팔로우하지 않았습니다. 탐색 탭에서 새로운 콘텐츠를 확인하세요!',
    anonymousUser: '익명',
    reportBtn: '신고',
    editPostBtn: '수정',
    deletePostBtn: '삭제',
    mediaCountWord: '미디어',
    shareBtn: '공유',
    likesModalTitle: '좋아요',
    noLikesYet: '아직 좋아요가 없습니다.',
    loading: '로딩 중...',
    commentsTitle: '댓글',
    firstCommentPrompt: '댓글이 없습니다. 첫 번째 댓글을 남겨보세요!',
    noComments: '작성된 댓글이 없습니다.',
    writeCommentPlaceholder: '댓글을 입력하세요...',
    sendCommentBtn: '게시',
    cancelBtn: '취소',
    saveBtn: '저장',

    reportModalTitle: '스팟 신고',
    reportModalSubtitle: '이 게시물의 문제점을 파악할 수 있도록 도와주세요.',
    reportReason: '사유',
    reportReasonSelect: '카테고리를 선택하세요...',
    reportCopyright: '저작권 침해',
    reportGdpr: '개인정보 침해 (GDPR)',
    reportHarassment: '괴롭힘, 협박 또는 혐오 발언',
    reportSpam: '스팸 또는 사기',
    reportOther: '부적절하거나 관련 없는 콘텐츠',
    reportDetails: '추가 설명 (선택사항)',
    reportDetailsPlaceholder: '자세한 정보를 입력하세요...',
    sendReportBtn: '신고 제출'
};