export default {
    spotTitle: 'Spots - Spottio',
    tabExplore: 'Ontdekken',
    tabFollowing: 'Volgend',
    yourFlashspot: 'Jouw Flashspot',
    noSpotsAvailable: 'Geen spots beschikbaar.',
    noFollowingSpots: 'Je volgt nog niemand. Ga naar Ontdekken voor nieuwe content!',
    anonymousUser: 'Anoniem',
    reportBtn: 'Rapporteren',
    editPostBtn: 'Bewerken',
    deletePostBtn: 'Verwijderen',
    mediaCountWord: 'media',
    shareBtn: 'Delen',
    likesModalTitle: 'Likes',
    noLikesYet: 'Nog geen likes.',
    loading: 'Laden...',
    commentsTitle: 'Reacties',
    firstCommentPrompt: 'Geen reacties. Wees de eerste om te reageren!',
    noComments: 'Geen reacties beschikbaar.',
    writeCommentPlaceholder: 'Schrijf een reactie...',
    sendCommentBtn: 'Versturen',
    cancelBtn: 'Annuleren',
    saveBtn: 'Opslaan',

    reportModalTitle: 'Spot rapporteren',
    reportModalSubtitle: 'Help ons te begrijpen wat het probleem is met deze inhoud.',
    reportReason: 'Reden',
    reportReasonSelect: 'Selecteer een categorie...',
    reportCopyright: 'Auteursrechtschending',
    reportGdpr: 'Schending van privacy / Persoonsgegevens (AVG)',
    reportHarassment: 'Intimidatie, bedreigingen of haatzaaien',
    reportSpam: 'Spam of fraude',
    reportOther: 'Niet-relevante inhoud',
    reportDetails: 'Extra details (Optioneel)',
    reportDetailsPlaceholder: 'Geef extra informatie...',
    sendReportBtn: 'Rapport versturen'
};