export default {
    spotTitle: 'Spoty - Spottio',
    tabExplore: 'Odkrywaj',
    tabFollowing: 'Obserwowani',
    yourFlashspot: 'Twój Flashspot',
    noSpotsAvailable: 'Brak dostępnych spotów.',
    noFollowingSpots: 'Jeszcze nikogo nie obserwujesz. Przejdź do Odkrywaj!',
    anonymousUser: 'Anonim',
    reportBtn: 'Zgłoś',
    editPostBtn: 'Edytuj',
    deletePostBtn: 'Usuń',
    mediaCountWord: 'multimedia',
    shareBtn: 'Udostępnij',
    likesModalTitle: 'Polubienia',
    noLikesYet: 'Brak polubień.',
    loading: 'Ładowanie...',
    commentsTitle: 'Komentarze',
    firstCommentPrompt: 'Brak komentarzy. Bądź pierwszą osobą, która skomentuje!',
    noComments: 'Brak dostępnych komentarzy.',
    writeCommentPlaceholder: 'Napisz komentarz...',
    sendCommentBtn: 'Wyślij',
    cancelBtn: 'Anuluj',
    saveBtn: 'Zapisz',

    reportModalTitle: 'Zgłoś spot',
    reportModalSubtitle: 'Pomóż nam zrozumieć problem z tą zawartością.',
    reportReason: 'Powód',
    reportReasonSelect: 'Wybierz kategorię...',
    reportCopyright: 'Naruszenie praw autorskich',
    reportGdpr: 'Naruszenie prywatności / Danych osobowych (RODO)',
    reportHarassment: 'Nękanie, groźby lub nienawiść',
    reportSpam: 'Spam lub oszustwo',
    reportOther: 'Nieistotna zawartość',
    reportDetails: 'Dodatkowe szczegóły (Opcjonalnie)',
    reportDetailsPlaceholder: 'Podaj dodatkowe informacje...',
    sendReportBtn: 'Wyślij zgłoszenie'
};