export default {
    spotTitle: 'Споты - Spottio',
    tabExplore: 'Интересное',
    tabFollowing: 'Подписки',
    yourFlashspot: 'Ваш Flashspot',
    noSpotsAvailable: 'Нет доступных спотов.',
    noFollowingSpots: 'Вы еще ни на кого не подписаны. Перейдите в раздел Интересное!',
    anonymousUser: 'Аноним',
    reportBtn: 'Пожаловаться',
    editPostBtn: 'Изменить',
    deletePostBtn: 'Удалить',
    mediaCountWord: 'медиа',
    shareBtn: 'Поделиться',
    likesModalTitle: 'Лайки',
    noLikesYet: 'Лайков пока нет.',
    loading: 'Загрузка...',
    commentsTitle: 'Комментарии',
    firstCommentPrompt: 'Нет комментариев. Будьте первым!',
    noComments: 'Комментариев нет.',
    writeCommentPlaceholder: 'Написать комментарий...',
    sendCommentBtn: 'Отправить',
    cancelBtn: 'Отмена',
    saveBtn: 'Сохранить',

    reportModalTitle: 'Пожаловаться на спот',
    reportModalSubtitle: 'Помогите нам понять, в чем проблема с этим материалом.',
    reportReason: 'Причина',
    reportReasonSelect: 'Выберите категорию...',
    reportCopyright: 'Нарушение авторских прав',
    reportGdpr: 'Нарушение конфиденциальности (GDPR)',
    reportHarassment: 'Оскорбления, угрозы или вражда',
    reportSpam: 'Спам или мошенничество',
    reportOther: 'Неуместный контент',
    reportDetails: 'Дополнительные сведения (Необязательно)',
    reportDetailsPlaceholder: 'Укажите дополнительную информацию...',
    sendReportBtn: 'Отправить жалобу'
};