export default {
    spotTitle: '动态 - Spottio',
    tabExplore: '探索',
    tabFollowing: '关注',
    yourFlashspot: '你的 Flashspot',
    noSpotsAvailable: '暂无可用动态。',
    noFollowingSpots: '你还没有关注任何人。前往探索页面发现新内容吧！',
    anonymousUser: '匿名用户',
    reportBtn: '举报',
    editPostBtn: '编辑',
    deletePostBtn: '删除',
    mediaCountWord: '媒体',
    shareBtn: '分享',
    likesModalTitle: '赞',
    noLikesYet: '暂无赞。',
    loading: '加载中...',
    commentsTitle: '评论',
    firstCommentPrompt: '暂无评论。抢先发表你的看法！',
    noComments: '暂无评论。',
    writeCommentPlaceholder: '写下你的评论...',
    sendCommentBtn: '发送',
    cancelBtn: '取消',
    saveBtn: '保存',

    reportModalTitle: '举报动态',
    reportModalSubtitle: '请帮助我们了解此内容的问题所在。',
    reportReason: '原因',
    reportReasonSelect: '请选择一个分类...',
    reportCopyright: '侵犯版权 / 知识产权',
    reportGdpr: '侵犯隐私 / 个人信息安全 (GDPR)',
    reportHarassment: '骚扰、恐吓或仇恨言论',
    reportSpam: '垃圾广告或诈骗',
    reportOther: '无关或琐碎内容',
    reportDetails: '补充说明（可选）',
    reportDetailsPlaceholder: '提供更多信息...',
    sendReportBtn: '提交举报'
};