export default {
    profileTitle: 'الملف الشخصي - Spottio',
    editUsernameTitle: 'تعديل اسم المستخدم',
    shareProfileTitle: 'مشاركة الملف الشخصي',
    followRequestsTitle: 'طلبات المتابعة',
    settingsTitle: 'الإعدادات',
    noBio: 'لا توجد سيرة ذاتية',
    editBioTitle: 'تعديل السيرة الذاتية',
    postWord: 'المنشورات',
    followersText: 'المتابعون',
    followingText: 'يتابع',
    likesWord: 'إعجابات',
    newUsernameLabel: 'اسم مستخدم جديد',
    newBioLabel: 'سيرة ذاتية جديدة',
    cancelBtn: 'إلغاء',
    saveBtn: 'حفظ',
    highlightTitle: 'القصص المميزة',
    loadingPosts: 'جاري تحميل منشوراتك...',
    noPostsFound: 'لا توجد منشورات.',
    editPostBtn: 'تعديل',
    deletePostBtn: 'حذف',
    mediaCountWord: 'وسائط',
    commentsTitle: 'التعليقات',
    noComments: 'لا توجد تعليقات.',
    anonymousUser: 'مجهول',
    writeCommentPlaceholder: 'اكتب تعليقاً...',
    sendCommentBtn: 'إرسال',
    yourFollowersTitle: 'متابعوك',
    followingUsersTitle: 'المستخدمون المتابعون',
    noUsers: 'لا يوجد مستخدمون.',
    removeFollowerBtn: 'إزالة',
    unfollowBtn: 'إلغاء المتابعة',
    likedSpotsTitle: 'المنشورات المعجب بها',
    loadingRequests: 'جاري تحميل الطلبات...',
    noPendingRequests: 'لا توجد طلبات معلقة.',
    viewFlashspotBtn: 'عرض القصة',
    changeAvatarBtn: 'تغيير الصورة الشخصية',
    likesModalTitle: 'الإعجابات',
    scanQrDesc: 'امسح الرمز لعرض الملف الشخصي',
    shareQrBtn: 'مشاركة رمز QR (صورة)',
    copyProfileLinkBtn: 'نسخ رابط الملف الشخصي',
    linkCopiedMsg: 'تم نسخ الرابط!',
    confirmUnfollow: 'هل تريد إلغاء متابعة هذا المستخدم؟',
    confirmRemoveFollower: 'هل تريد إزالة هذا المتابع؟ لن يتلقى أي إشعار.'
};