export default {
    profileTitle: 'Profile - Spottio',
    editUsernameTitle: 'Edit Username',
    shareProfileTitle: 'Share Profile',
    followRequestsTitle: 'Follow Requests',
    settingsTitle: 'Settings',
    noBio: 'No bio set',
    editBioTitle: 'Edit Bio',
    postWord: 'Spots',
    followersText: 'Followers',
    followingText: 'Following',
    likesWord: 'Likes',
    newUsernameLabel: 'New Username',
    newBioLabel: 'New Bio',
    cancelBtn: 'Cancel',
    saveBtn: 'Save',
    highlightTitle: 'Featured Flashspots',
    loadingPosts: 'Loading your spots...',
    noPostsFound: 'No spots found.',
    editPostBtn: 'Edit',
    deletePostBtn: 'Delete',
    mediaCountWord: 'media',
    commentsTitle: 'Comments',
    noComments: 'No comments.',
    anonymousUser: 'Anonymous',
    writeCommentPlaceholder: 'Write a comment...',
    sendCommentBtn: 'Send',
    yourFollowersTitle: 'Your Followers',
    followingUsersTitle: 'Followed Users',
    noUsers: 'No users.',
    removeFollowerBtn: 'Remove',
    unfollowBtn: 'Unfollow',
    likedSpotsTitle: 'Liked spots',
    loadingRequests: 'Loading requests...',
    noPendingRequests: 'No pending requests.',
    viewFlashspotBtn: 'View Flashspot',
    changeAvatarBtn: 'Change profile picture',
    likesModalTitle: 'Likes',
    scanQrDesc: 'Scan to view profile',
    shareQrBtn: 'Share QR Code (Image)',
    copyProfileLinkBtn: 'Copy Profile Link',
    linkCopiedMsg: 'Link Copied!',
    confirmUnfollow: 'Do you want to unfollow this user?',
    confirmRemoveFollower: 'Do you want to remove this follower? They will not be notified.'
};