export default {
    profileTitle: 'Perfil - Spottio',
    editUsernameTitle: 'Editar nombre de usuario',
    shareProfileTitle: 'Compartir perfil',
    followRequestsTitle: 'Solicitudes de seguimiento',
    settingsTitle: 'Ajustes',
    noBio: 'Sin biografía',
    editBioTitle: 'Editar Bio',
    postWord: 'Spots',
    followersText: 'Seguidores',
    followingText: 'Siguiendo',
    likesWord: 'Me gusta',
    newUsernameLabel: 'Nuevo nombre de usuario',
    newBioLabel: 'Nueva biografía',
    cancelBtn: 'Cancelar',
    saveBtn: 'Guardar',
    highlightTitle: 'Flashspots destacados',
    loadingPosts: 'Cargando tus spots...',
    noPostsFound: 'No se encontraron posts.',
    editPostBtn: 'Editar',
    deletePostBtn: 'Eliminar',
    mediaCountWord: 'archivos',
    commentsTitle: 'Comentarios',
    noComments: 'No hay comentarios.',
    anonymousUser: 'Anónimo',
    writeCommentPlaceholder: 'Escribe un comentario...',
    sendCommentBtn: 'Enviar',
    yourFollowersTitle: 'Tus Seguidores',
    followingUsersTitle: 'Usuarios Seguidos',
    noUsers: 'No hay usuarios.',
    removeFollowerBtn: 'Eliminar',
    unfollowBtn: 'Dejar de seguir',
    likedSpotsTitle: 'Spots que te gustan',
    loadingRequests: 'Cargando solicitudes...',
    noPendingRequests: 'No hay solicitudes pendientes.',
    viewFlashspotBtn: 'Ver Flashspot',
    changeAvatarBtn: 'Cambiar foto de perfil',
    likesModalTitle: 'Me gusta',
    scanQrDesc: 'Escanea para ver el perfil',
    shareQrBtn: 'Compartir Código QR (Imagen)',
    copyProfileLinkBtn: 'Copiar enlace del perfil',
    linkCopiedMsg: '¡Enlace copiado!',
    confirmUnfollow: '¿Quieres dejar de seguir a este usuario?',
    confirmRemoveFollower: '¿Quieres eliminar a este seguidor? No recibirá ninguna notificación.'
};