export default {
    profileTitle: 'Profil - Spottio',
    editUsernameTitle: 'Modifier le nom d\'utilisateur',
    shareProfileTitle: 'Partager le profil',
    followRequestsTitle: 'Demandes d\'abonnement',
    settingsTitle: 'Paramètres',
    noBio: 'Aucune bio',
    editBioTitle: 'Modifier la Bio',
    postWord: 'Spots',
    followersText: 'Abonnés',
    followingText: 'Abonnements',
    likesWord: 'J\'aime',
    newUsernameLabel: 'Nouveau nom d\'utilisateur',
    newBioLabel: 'Nouvelle bio',
    cancelBtn: 'Annuler',
    saveBtn: 'Enregistrer',
    highlightTitle: 'Flashspots à la une',
    loadingPosts: 'Chargement de vos spots...',
    noPostsFound: 'Aucun spot trouvé.',
    editPostBtn: 'Modifier',
    deletePostBtn: 'Supprimer',
    mediaCountWord: 'médias',
    commentsTitle: 'Commentaires',
    noComments: 'Aucun commentaire.',
    anonymousUser: 'Anonyme',
    writeCommentPlaceholder: 'Écrire un commentaire...',
    sendCommentBtn: 'Envoyer',
    yourFollowersTitle: 'Vos Abonnés',
    followingUsersTitle: 'Utilisateurs Suivis',
    noUsers: 'Aucun utilisateur.',
    removeFollowerBtn: 'Retirer',
    unfollowBtn: 'Se désabonner',
    likedSpotsTitle: 'Spots aimés',
    loadingRequests: 'Chargement des demandes...',
    noPendingRequests: 'Aucune demande en attente.',
    viewFlashspotBtn: 'Voir le Flashspot',
    changeAvatarBtn: 'Changer la photo de profil',
    likesModalTitle: 'J\'aime',
    scanQrDesc: 'Scannez pour voir le profil',
    shareQrBtn: 'Partager le QR Code (Image)',
    copyProfileLinkBtn: 'Copier le lien du profil',
    linkCopiedMsg: 'Lien copié !',
    confirmUnfollow: 'Voulez-vous ne plus suivre cet utilisateur ?',
    confirmRemoveFollower: 'Voulez-vous supprimer cet abonné ? Aucune notification ne lui sera envoyée.'
};