export default {
    profileTitle: 'प्रोफ़ाइल - Spottio',
    editUsernameTitle: 'उपयोगकर्ता नाम संपादित करें',
    shareProfileTitle: 'प्रोफ़ाइल साझा करें',
    followRequestsTitle: 'फ़ॉलो अनुरोध',
    settingsTitle: 'सेटिंग्स',
    noBio: 'कोई बायो नहीं',
    editBioTitle: 'बायो संपादित करें',
    postWord: 'स्पॉट',
    followersText: 'फ़ॉलोअर्स',
    followingText: 'फ़ॉलो कर रहे हैं',
    likesWord: 'पसंद',
    newUsernameLabel: 'नया उपयोगकर्ता नाम',
    newBioLabel: 'नया बायो',
    cancelBtn: 'रद्द करें',
    saveBtn: 'सहेजें',
    highlightTitle: 'फ़्लैशस्पॉट हाइलाइट्स',
    loadingPosts: 'आपके स्पॉट लोड हो रहे हैं...',
    noPostsFound: 'कोई स्पॉट नहीं मिला।',
    editPostBtn: 'संपादित करें',
    deletePostBtn: 'हटाएं',
    mediaCountWord: 'मीडिया',
    commentsTitle: 'टिप्पणियाँ',
    noComments: 'कोई टिप्पणी नहीं।',
    anonymousUser: 'अनाम',
    writeCommentPlaceholder: 'एक टिप्पणी लिखें...',
    sendCommentBtn: 'भेजें',
    yourFollowersTitle: 'आपके फ़ॉलोअर्स',
    followingUsersTitle: 'फॉलो किए गए उपयोगकर्ता',
    noUsers: 'कोई उपयोगकर्ता नहीं।',
    removeFollowerBtn: 'हटाएं',
    unfollowBtn: 'अनफ़ॉलो करें',
    likedSpotsTitle: 'पसंद किए गए स्पॉट',
    loadingRequests: 'अनुरोध लोड हो रहे हैं...',
    noPendingRequests: 'कोई लंबित अनुरोध नहीं।',
    viewFlashspotBtn: 'फ़्लैशस्पॉट देखें',
    changeAvatarBtn: 'प्रोफ़ाइल फ़ोटो बदलें',
    likesModalTitle: 'पसंद',
    scanQrDesc: 'प्रोफ़ाइल देखने के लिए स्कैन करें',
    shareQrBtn: 'क्यूआर कोड साझा करें (छवि)',
    copyProfileLinkBtn: 'प्रोफ़ाइल लिंक कॉपी करें',
    linkCopiedMsg: 'लिंक कॉपी हो गया!',
    confirmUnfollow: 'क्या आप इस उपयोगकर्ता को अनफ़ॉलो करना चाहते हैं?',
    confirmRemoveFollower: 'क्या आप इस फ़ॉलोअर को हटाना चाहते हैं? उन्हें सूचित नहीं किया जाएगा।'
};