export default {
    profileTitle: 'Profilo - Spottio',
    editUsernameTitle: 'Modifica Username',
    shareProfileTitle: 'Condividi Profilo',
    followRequestsTitle: 'Richieste di Follow',
    settingsTitle: 'Impostazioni',
    noBio: 'Nessuna bio impostata',
    editBioTitle: 'Modifica Bio',
    postWord: 'Spot',
    followersText: 'Follower',
    followingText: 'Seguiti',
    likesWord: 'Like',
    newUsernameLabel: 'Nuovo Username',
    newBioLabel: 'Nuova Bio',
    cancelBtn: 'Annulla',
    saveBtn: 'Salva',
    highlightTitle: 'Flashspot in evidenza',
    loadingPosts: 'Caricamento dei tuoi spot...',
    noPostsFound: 'Nessun post trovato.',
    editPostBtn: 'Modifica',
    deletePostBtn: 'Elimina',
    mediaCountWord: 'media',
    commentsTitle: 'Commenti',
    noComments: 'Nessun commento.',
    anonymousUser: 'Anonimo',
    writeCommentPlaceholder: 'Scrivi un commento...',
    sendCommentBtn: 'Invia',
    yourFollowersTitle: 'I tuoi Follower',
    followingUsersTitle: 'Utenti Seguiti',
    noUsers: 'Nessun utente.',
    removeFollowerBtn: 'Rimuovi',
    unfollowBtn: 'Non seguire più',
    likedSpotsTitle: 'Spot piaciuti',
    loadingRequests: 'Caricamento richieste...',
    noPendingRequests: 'Nessuna richiesta in attesa.',
    viewFlashspotBtn: 'Visualizza Flashspot',
    changeAvatarBtn: 'Cambia immagine profilo',
    likesModalTitle: 'Mi piace',
    scanQrDesc: 'Scansiona per visualizzare il profilo',
    shareQrBtn: 'Condividi QR Code (Immagine)',
    copyProfileLinkBtn: 'Copia Link del Profilo',
    linkCopiedMsg: 'Link Copiato!',
    confirmUnfollow: 'Vuoi smettere di seguire questo utente?',
    confirmRemoveFollower: 'Vuoi rimuovere questo follower? Non riceverà alcuna notifica.'
};