export default {
    profileTitle: '프로필 - Spottio',
    editUsernameTitle: '사용자 이름 수정',
    shareProfileTitle: '프로필 공유',
    followRequestsTitle: '팔로우 요청',
    settingsTitle: '설정',
    noBio: '소개 없음',
    editBioTitle: '소개 수정',
    postWord: '게시물',
    followersText: '팔로워',
    followingText: '팔로잉',
    likesWord: '좋아요',
    newUsernameLabel: '새 사용자 이름',
    newBioLabel: '새 소개',
    cancelBtn: '취소',
    saveBtn: '저장',
    highlightTitle: '하이라이트 플래시스팟',
    loadingPosts: '게시물 로딩 중...',
    noPostsFound: '게시물이 없습니다.',
    editPostBtn: '수정',
    deletePostBtn: '삭제',
    mediaCountWord: '미디어',
    commentsTitle: '댓글',
    noComments: '댓글이 없습니다.',
    anonymousUser: '익명',
    writeCommentPlaceholder: '댓글을 입력하세요...',
    sendCommentBtn: '게시',
    yourFollowersTitle: '팔로워',
    followingUsersTitle: '팔로잉',
    noUsers: '사용자 없음.',
    removeFollowerBtn: '삭제',
    unfollowBtn: '언팔로우',
    likedSpotsTitle: '좋아요한 스팟',
    loadingRequests: '요청 로딩 중...',
    noPendingRequests: '대기 중인 요청이 없습니다.',
    viewFlashspotBtn: '플래시스팟 보기',
    changeAvatarBtn: '프로필 사진 변경',
    likesModalTitle: '좋아요',
    scanQrDesc: '스캔하여 프로필 보기',
    shareQrBtn: 'QR 코드 공유 (이미지)',
    copyProfileLinkBtn: '프로필 링크 복사',
    linkCopiedMsg: '링크가 복사되었습니다!',
    confirmUnfollow: '이 사용자를 언팔로우하시겠습니까?',
    confirmRemoveFollower: '이 팔로워를 삭제하시겠습니까? 상대방에게 알림이 가지 않습니다.'
};