export default {
    profileTitle: 'Profiel - Spottio',
    editUsernameTitle: 'Gebruikersnaam bewerken',
    shareProfileTitle: 'Profiel delen',
    followRequestsTitle: 'Volgverzoeken',
    settingsTitle: 'Instellingen',
    noBio: 'Geen bio',
    editBioTitle: 'Bio bewerken',
    postWord: 'Spots',
    followersText: 'Volgers',
    followingText: 'Volgend',
    likesWord: 'Likes',
    newUsernameLabel: 'Nieuwe gebruikersnaam',
    newBioLabel: 'Nieuwe bio',
    cancelBtn: 'Annuleren',
    saveBtn: 'Opslaan',
    highlightTitle: 'Uitgelichte Flashspots',
    loadingPosts: 'Berichten laden...',
    noPostsFound: 'Geen berichten gevonden.',
    editPostBtn: 'Bewerken',
    deletePostBtn: 'Verwijderen',
    mediaCountWord: 'media',
    commentsTitle: 'Reacties',
    noComments: 'Geen reacties.',
    anonymousUser: 'Anoniem',
    writeCommentPlaceholder: 'Schrijf een reactie...',
    sendCommentBtn: 'Versturen',
    yourFollowersTitle: 'Jouw Volgers',
    followingUsersTitle: 'Gevolgde Gebruikers',
    noUsers: 'Geen gebruikers.',
    removeFollowerBtn: 'Verwijderen',
    unfollowBtn: 'Ontvolgen',
    likedSpotsTitle: 'Gelikete spots',
    loadingRequests: 'Verzoeken laden...',
    noPendingRequests: 'Geen openstaande verzoeken.',
    viewFlashspotBtn: 'Flashspot bekijken',
    changeAvatarBtn: 'Profielfoto wijzigen',
    likesModalTitle: 'Likes',
    scanQrDesc: 'Scan om profiel te bekijken',
    shareQrBtn: 'QR-code delen (Afbeelding)',
    copyProfileLinkBtn: 'Profiellink kopiëren',
    linkCopiedMsg: 'Link gekopieerd!',
    confirmUnfollow: 'Wil je deze gebruiker ontvolgen?',
    confirmRemoveFollower: 'Wil je deze volger verwijderen? Er wordt geen melding gestuurd.'
};