export default {
    profileTitle: 'Profil - Spottio',
    editUsernameTitle: 'Edytuj nazwę użytkownika',
    shareProfileTitle: 'Udostępnij profil',
    followRequestsTitle: 'Prośby o obserwację',
    settingsTitle: 'Ustawienia',
    noBio: 'Brak bio',
    editBioTitle: 'Edytuj Bio',
    postWord: 'Spoty',
    followersText: 'Obserwujący',
    followingText: 'Obserwowani',
    likesWord: 'Polubienia',
    newUsernameLabel: 'Nowa nazwa użytkownika',
    newBioLabel: 'Nowe bio',
    cancelBtn: 'Anuluj',
    saveBtn: 'Zapisz',
    highlightTitle: 'Wyróżnione Flashspoty',
    loadingPosts: 'Ładowanie postów...',
    noPostsFound: 'Nie znaleziono postów.',
    editPostBtn: 'Edytuj',
    deletePostBtn: 'Usuń',
    mediaCountWord: 'multimedia',
    commentsTitle: 'Komentarze',
    noComments: 'Brak komentarzy.',
    anonymousUser: 'Anonim',
    writeCommentPlaceholder: 'Napisz komentarz...',
    sendCommentBtn: 'Wyślij',
    yourFollowersTitle: 'Twoi Obserwujący',
    followingUsersTitle: 'Obserwowani',
    noUsers: 'Brak użytkowników.',
    removeFollowerBtn: 'Usuń',
    unfollowBtn: 'Przestań obserwować',
    likedSpotsTitle: 'Polubione spoty',
    loadingRequests: 'Ładowanie próśb...',
    noPendingRequests: 'Brak oczekujących próśb.',
    viewFlashspotBtn: 'Zobacz Flashspot',
    changeAvatarBtn: 'Zmień zdjęcie profilowe',
    likesModalTitle: 'Polubienia',
    scanQrDesc: 'Zeskanuj, aby zobaczyć profil',
    shareQrBtn: 'Udostępnij kod QR (Obraz)',
    copyProfileLinkBtn: 'Kopiuj link do profilu',
    linkCopiedMsg: 'Link skopiowany!',
    confirmUnfollow: 'Czy na pewno chcesz przestać obserwować tego użytkownika?',
    confirmRemoveFollower: 'Czy chcesz usunąć tego obserwującego? Nie otrzyma powiadomienia.'
};