export default {
    profileTitle: 'Профиль - Spottio',
    editUsernameTitle: 'Изменить имя пользователя',
    shareProfileTitle: 'Поделиться профилем',
    followRequestsTitle: 'Запросы на подписку',
    settingsTitle: 'Настройки',
    noBio: 'Био не указано',
    editBioTitle: 'Редактировать Био',
    postWord: 'Споты',
    followersText: 'Подписчики',
    followingText: 'Подписки',
    likesWord: 'Лайки',
    newUsernameLabel: 'Новое имя пользователя',
    newBioLabel: 'Новое био',
    cancelBtn: 'Отмена',
    saveBtn: 'Сохранить',
    highlightTitle: 'Избранные истории',
    loadingPosts: 'Загрузка ваших постов...',
    noPostsFound: 'Посты не найдены.',
    editPostBtn: 'Изменить',
    deletePostBtn: 'Удалить',
    mediaCountWord: 'медиа',
    commentsTitle: 'Комментарии',
    noComments: 'Нет комментариев.',
    anonymousUser: 'Аноним',
    writeCommentPlaceholder: 'Написать комментарий...',
    sendCommentBtn: 'Отправить',
    yourFollowersTitle: 'Ваши Подписчики',
    followingUsersTitle: 'Вы подписаны',
    noUsers: 'Нет пользователей.',
    removeFollowerBtn: 'Удалить',
    unfollowBtn: 'Отписаться',
    likedSpotsTitle: 'Понравившиеся споты',
    loadingRequests: 'Загрузка запросов...',
    noPendingRequests: 'Нет запросов в ожидании.',
    viewFlashspotBtn: 'Смотреть Flashspot',
    changeAvatarBtn: 'Изменить аватар',
    likesModalTitle: 'Лайки',
    scanQrDesc: 'Отсканируйте для перехода в профиль',
    shareQrBtn: 'Поделиться QR-кодом (Фото)',
    copyProfileLinkBtn: 'Скопировать ссылку',
    linkCopiedMsg: 'Ссылка скопирована!',
    confirmUnfollow: 'Вы уверены, что хотите отписаться от пользователя?',
    confirmRemoveFollower: 'Удалить подписчика? Уведомление отправлено не будет.'
};