export default {
    profileTitle: '个人资料 - Spottio',
    editUsernameTitle: '修改用户名',
    shareProfileTitle: '分享主页',
    followRequestsTitle: '关注请求',
    settingsTitle: '设置',
    noBio: '暂无简介',
    editBioTitle: '编辑简介',
    postWord: 'Spot',
    followersText: '粉丝',
    followingText: '关注',
    likesWord: '赞',
    newUsernameLabel: '新用户名',
    newBioLabel: '新简介',
    cancelBtn: '取消',
    saveBtn: '保存',
    highlightTitle: '精选 Flashspot',
    loadingPosts: '加载帖子中...',
    noPostsFound: '未找到帖子。',
    editPostBtn: '编辑',
    deletePostBtn: '删除',
    mediaCountWord: '媒体',
    commentsTitle: '评论',
    noComments: '暂无评论。',
    anonymousUser: '匿名用户',
    writeCommentPlaceholder: '写一条评论...',
    sendCommentBtn: '发送',
    yourFollowersTitle: '您的粉丝',
    followingUsersTitle: '关注的人',
    noUsers: '没有用户。',
    removeFollowerBtn: '移除',
    unfollowBtn: '取消关注',
    likedSpotsTitle: '赞过的Spot',
    loadingRequests: '加载请求中...',
    noPendingRequests: '暂无待处理请求。',
    viewFlashspotBtn: '查看 Flashspot',
    changeAvatarBtn: '更换头像',
    likesModalTitle: '点赞列表',
    scanQrDesc: '扫码查看个人资料',
    shareQrBtn: '分享二维码 (图片)',
    copyProfileLinkBtn: '复制主页链接',
    linkCopiedMsg: '链接已复制！',
    confirmUnfollow: '确定要取消关注该用户吗？',
    confirmRemoveFollower: '确定要移除此粉丝吗？对方不会收到通知。'
};